# SwiftLint configuration for ClipCook

included:
  - ClipCook
  - ClipCookShareExtension

excluded:
  - ClipCook/Resources
  - ClipCookTests
  - ClipCookUITests

# Rules
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - closure_spacing
  - force_unwrapping
  - implicitly_unwrapped_optional
  - sorted_imports

# Configuration
line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - db
    - ui
